<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Thomas Kurth</Authors>
    <Product>GetHarvest API Client</Product>
    <Description>This library allows connecting to the Harvest Timetracking API v2 and requesting and modifying all entities from there. https://www.getharvest.com/
Instead of other library it is using the new version 2 OAuth based API.</Description>
    <PackageLicenseUrl>https://github.com/ThomasKur/baseVISION.Tool.Connectors.Harvest/blob/master/LICENSE</PackageLicenseUrl>
    <Copyright>Thomas Kurth</Copyright>
    <PackageProjectUrl>https://github.com/ThomasKur/baseVISION.Tool.Connectors.Harvest/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ThomasKur/baseVISION.Tool.Connectors.Harvest/</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageReleaseNotes>See Readme.</PackageReleaseNotes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <AssemblyVersion>2.1.2.0</AssemblyVersion>
    <FileVersion>2.1.1.0</FileVersion>
    <Version>2.1.3</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="Pack">
		<Exec Command="xcopy &quot;$(TargetDir)..\*.nupkg&quot; &quot;C:\LocalLibrary&quot; /C /Y" />
	</Target>
</Project>